plugins {
    id "com.android.application"
}

android {
    namespace "com.elysiapoi.tianyangschedule"
    compileSdk 36

    defaultConfig {
        applicationId "com.elysiapoi.tianyangschedule"
        minSdk 24
        targetSdk 36
        versionCode 15
        versionName "1.2.4"
    }

    sourceSets {
        main.assets.srcDirs = ["../../dist/client"]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.17.0"
}
